Repository AY2021S2-CS2103-T16-3/tp, pull requests merged in 2021-03, with the labels that each got.

#47 Update DeveloperGuide.md: Use Cases
  docs/DeveloperGuide.md
Labels: documentation

#78 Fixed breaking tests expect the parser classes
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/residence/Booking.java
  src/main/java/seedu/address/model/residence/BookingDetails.java
  src/main/java/seedu/address/model/residence/Residence.java
  src/main/java/seedu/address/model/residence/ResidenceAddress.java
  src/main/java/seedu/address/model/residence/ResidenceName.java
  src/main/java/seedu/address/model/tag/CleanStatusTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCleanStatusTag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedResidence.java
  src/main/java/seedu/address/storage/JsonResidenceTrackerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableResidenceTracker.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResidenceCard.java
  src/main/resources/view/ResidenceListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ResidenceTrackerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/residence/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableResidenceTrackerTest.java
  src/test/java/seedu/address/testutil/EditResidenceDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ResidenceBuilder.java
  src/test/java/seedu/address/testutil/ResidenceUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalResidences.java
Labels: priority.High

#82 Update test cases (look at description for specific files)
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ResidenceTrackerParserTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/EditResidenceDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ResidenceUtil.java
  src/test/java/seedu/address/testutil/TypicalResidences.java
Labels: bug, priority.High

#119 Fix CommandException handling for AddBookingCommand
  src/main/java/seedu/address/logic/commands/AddBookingCommand.java
  src/main/java/seedu/address/model/booking/UniqueBookingList.java
  src/main/java/seedu/address/model/residence/Residence.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug

#122 Improve Ui to display a list of bookings under each residence
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddBookingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/booking/Booking.java
  src/main/java/seedu/address/model/residence/BookingList.java
  src/main/java/seedu/address/model/tag/CleanStatusTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResidenceCard.java
  src/main/java/seedu/address/ui/ResidenceListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResidenceListCard.fxml
Labels: enhancement

#140 Modified Ui's bookinglist showcase from FlowPane to ScrollPane
  docs/images/Ui.png
  src/main/java/seedu/address/model/residence/BookingList.java
  src/main/java/seedu/address/ui/ResidenceCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResidenceListCard.fxml
Labels: enhancement

#144 Updated Ui to allow ScrollPane to stretch with MainWindow
  src/main/java/seedu/address/ui/ResidenceCard.java
  src/main/resources/view/ResidenceListCard.fxml
Labels: enhancement

#160 Fixed bug where long booking spills out of pink text highlight
  src/main/resources/images/background.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResidenceListCard.fxml
Labels: bug

#162 Updated Ui: 3 colors for upcoming, occurring & expired bookings.
  src/main/java/seedu/address/ui/ResidenceCard.java
  src/main/resources/view/DarkTheme.css
Labels: enhancement
